### ISSUE TITLE
Deleting a marked clone removes the mark from allMarks

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#67] opened 2015-10-15 02:24 UTC
1. Mark a row
2. Clone the row
3. Delete either copy of the row, let's say the original.
4. Search for that mark

This fails.

**Comment by paulfchristiano** [comment] 2015-10-19 20:02
Marks still seem to behave badly with cloning. If you clone a node it looks like it removes all marks, which would maybe be OK behavior. But the mark is still somewhere, and you can search for it / can't use the name for anything else.

Moreover, if you then delete the node, it throws the error below. This seems to stop the page from loading in the future (I'm not sure how to recover my data now, I'll expect to wait until the issue is resolved).

"Caught error: 'Error: Assertion error: No parent found for id: 420658
Expected false to be true' from  http://localhost:8080/js/errors.js:9" logger.js:51:18
Error:  Object { message: "Assertion error: No parent found fo…", stack: "errorFactory@http://localhost:8080/…" } errorFactory@http://localhost:8080/js/errors.js:9:21
@http://localhost:8080/js/errors.js:24:22
@http://localhost:8080/js/errors.js:6:1
@http://localhost:8080/js/errors.js:1:1

**Comment by vanceza** [comment] 2015-10-19 20:48
That looks pretty bad, we don't want the page to be un-loadable. Can you give a set of reproduction steps from the starting state?

Please don't use non-master branches without backing up localstorage, I don't think we can completely guarantee data safety even on master. Also, can you include the commit you're on when reporting bugs on the aliasing branch, for future reference?

The expected behavior is that if you clone the mark, both copies have the mark, and searching for the mark brings you to a the 'canonical' clone [which is not yet well-defined].

**Comment by paulfchristiano** [comment] 2015-10-19 20:52
Sorry, this was on a previous commit, is now fixed. I opened a new issue with a complaint about the current behavior, which seems to only apply on my local copy. I'll include commits in the future.

**Closed** 2015-10-19 20:55 UTC

**Comment by paulfchristiano** [comment] 2015-10-19 22:34
Is there a way to backup local storage without exporting? Import/export takes a very long time for my document. (The document I lost was within 30m of the last backup, even if it is lost forever.)

**Comment by vanceza** [comment] 2015-10-19 22:53
On Chrome + Mac, it's saved to:
~/Library/Application Support/Google/Chrome/<user-profile>/Local Storage/

If you want to back it up, I'd recommend not running chrome during the backup just to be safe.

Obviously this blanket approach will affect other sites you visit.

I've also mitigated this issue a bit by versioning the data from now on.
