### ISSUE TITLE
Time tracking updating

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#223] opened 2016-12-12 05:48 UTC
The time tracking plugin displays the time as "20m + 30s." The "+ 30s" is supposed to appear next to the current bullet, but its location only seems to be refreshed when the display updates again.

If press j, then the "+ 30s" is replaced by a "+ 0s" on the bullet my cursor used to be on, rather than on the bullet my cursor is now on. This gets fixed when I press any key.

On commit 07c291c6544b256cd29

**Comment by WuTheFWasThat** [comment] 2016-12-13 03:19
bb0da0faa45d82cec156b04649e1d65a020036b7

**Comment by paulfchristiano** [comment] 2016-12-13 04:35
This isn't fixed for me in bb0da0f. (I get the problem when I enable time tracking, then open a fresh document.)

Also the first bullet I visit shows "NaN + 0s" rather than "0s + 0s," that doesn't really matter but it seems like a bad sign.

**Comment by WuTheFWasThat** [comment] 2016-12-13 06:00
I think the issue where the "+ 30s" appears on the previous bullet instead of the current one should be fixed, right?  If not, I can't reproduce

I also can't get NaN to show up (although I've seen it before).  do you know what conditions make it happen?

there is a problem where when you initially open the document, it doesn't show the +30s.  it should start logging as soon as you do something though

**Comment by paulfchristiano** [comment] 2016-12-13 18:38
Yes, the problem was fixed, I guess something got cached somewhere.

I still have the following very minor problem: row A says "1m + 1m". When I move to row B, row A now says "1m." The display updates to "2m" on the next keystroke.

**Comment by WuTheFWasThat** [comment] 2016-12-14 07:39
i fixed it at a cost of rendering slightly slower.  didn't seem noticeable to me, lemme know if it's an issue

**Closed by WuTheFWasThat** 2016-12-14 07:39 UTC
